# Generated by Django 4.1.1 on 2022-11-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="sobrenome",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.DateField(max_length=200),
        ),
    ]
